site_name: Saturn wiki
theme:
    name: material
    palette:
      primary: green
      secondary: green
    features:
      - content.code.annotate 


nav:
  - Tasks:
    - task: docpages/task/task.md
  - Gobjects: 
    - gobject: docpages/gobject/gobject.md 

plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        pt: Portugues

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets