site_name: Saturn wiki
theme:
    name: material
    palette:
      primary: green
      secondary: green


plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        pt: Portugues
