site_name: Saturn wiki
theme:
    name: material
    palette:
      primary: deep purple
      accent: yellow
    features:
      - content.code.annotate 
      - content.tabs.link
      - search.suggest
    logo: https://cdn.discordapp.com/attachments/534768096830029825/906337841003499520/ezgif.com-gif-maker_3.gif


nav:
  - Home : index.md
  - Tasks:
    - Task: docpages/task/task.md
    - Parallel Task: docpages/task/paraleltask.md
  - Gobjects: 
    - gobject: docpages/gobject/gobject.md 

plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        pt: Portugues
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - attr_list
  - md_in_html


extra_css:
  - stylesheets/extra.css